title: SMCC
description: St. Mary Community Centre
url: "https://nsamaan18.github.io"
baseurl: "/SMCCRental"
markdown: kramdown
theme: null

collections:
  pages:
    output: true
    permalink: /:name/
